name: Deploy to GitHub Pages

on:
  push:
    branches: main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false
# TODO: add other essential stuff soon (linting, formatting, etc.)
jobs:
  build:
    name: Build SvelteKit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: yarn install
      # - name: Check Formatters
      #   run: pnpm fmt
      # - name: Run All Lints in Parallel
      #   run: pnpm lint
      - name: Build Website
        run: yarn build
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build
  deploy:
    needs: build
    name: Deployment
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4